"""Target-neutral adapter contracts for later Android/Honda milestones.

These are extension points only. No Honda adapter is implemented by defining
one of these protocols, and R7A uses only the host media/display implementations.
"""
from __future__ import annotations

from typing import Callable, Protocol

from .decoder import DecodedFrame


class UsbIap2Transport(Protocol):
    def open(self) -> None: ...
    def read(self, maximum_bytes: int) -> bytes: ...
    def write(self, data: bytes) -> None: ...
    def close(self) -> None: ...


class ControlSessionTransport(Protocol):
    def exchange(self, generation: int, request: bytes) -> bytes: ...
    def close(self, generation: int) -> None: ...


class MediaTransport(Protocol):
    def bind(self, generation: int, stream_type: int, stream_connection_id: int) -> int: ...
    def receive(self, generation: int, stream_type: int, maximum_bytes: int) -> bytes: ...
    def close_stream(self, generation: int, stream_type: int) -> None: ...


class AudioOutput(Protocol):
    def write_pcm(self, generation: int, pcm: bytes, sample_rate: int, channels: int) -> None: ...
    def close(self, generation: int) -> None: ...


class InputControls(Protocol):
    def set_handler(self, handler: Callable[[int, bytes], None]) -> None: ...
    def close(self, generation: int) -> None: ...


class FrameOutput(Protocol):
    def show(self, frame: DecodedFrame) -> None: ...
    def clear(self) -> None: ...


class ProcessLifecycle(Protocol):
    def start(self, generation: int) -> None: ...
    def stop(self, generation: int) -> None: ...
