#!/usr/bin/env python3
"""Build local display metadata and file:// replay samples from copied evidence."""
import hashlib
import json
import pathlib
import struct
import xml.etree.ElementTree as ET

ROOT = pathlib.Path(__file__).resolve().parent
ANDROID = "{http://schemas.android.com/apk/res/android}"


def png_size(path):
    with path.open("rb") as source:
        header = source.read(24)
    if header[:8] != b"\x89PNG\r\n\x1a\n" or header[12:16] != b"IHDR":
        raise ValueError(f"Not a PNG: {path}")
    return struct.unpack(">II", header[16:24])


def sha256(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def make_profile():
    vendor_path = ROOT / "working-backup" / "j_config.xml"
    meter_path = ROOT / "working-backup" / "meter_civic.xml"
    vendor = ET.parse(vendor_path).getroot()
    meter = ET.parse(meter_path).getroot()
    width = int(vendor.find(".//VIDEO_WIDTH_PIXELS").attrib["Value"])
    height = int(vendor.find(".//VIDEO_HEIGHT_PIXELS").attrib["Value"])
    fps = int(vendor.find(".//MAX_FPS").attrib["Value"])
    meter_width = int(float(meter.attrib[ANDROID + "layout_width"].removesuffix("px")))
    meter_height = int(float(meter.attrib[ANDROID + "layout_height"].removesuffix("px")))
    files = {}
    for name in ("center-maps.png", "center-music.png", "cluster-navigation.png",
                 "center-20260925-native-maps.png", "cluster-20260925-native.png",
                 "center-20260925-cast-maps.png", "cluster-20260925-cast-maps.png",
                 "center-20260925-music.png", "cluster-20260925-cast-music.png"):
        path = ROOT / "assets" / name
        size = png_size(path)
        if size != (width, height):
            raise ValueError(f"Unexpected {name} size: {size}")
        files[name] = {"sha256": sha256(path), "width": size[0], "height": size[1]}
    profile = {
        "source": "working copies of backed-up j_config.xml and Honda Hack meter_civic.xml; saved read-only display captures",
        "center": {"width": width, "height": height, "configuredMaxFps": fps},
        "clusterHdmiCapture": {"width": width, "height": height},
        "meterLayout": {"width": meter_width, "height": meter_height,
                        "placementOnPhysicalCluster": "user reports cast in the NE compass/Navigation area; exact pixel boundary unmeasured"},
        "physicalClusterReferences": {
            name: {"image": "assets/" + name, "sha256": sha256(ROOT / "assets" / name)}
            for name in ("physical-cluster-20260925.jpg", "physical-maps-20260925.jpg",
                         "physical-carplay-home-20260925.jpg", "physical-music-20260925.jpg",
                         "physical-honda-home-20260925.jpg")
        },
        "physicalCastObservation": "wide central rectangle below speed and above Menu/trip row; speed/range visible; edge clearance near power/charge scales unverified",
        "files": files,
        "firmwareCopySha256": {"j_config.xml": sha256(vendor_path), "meter_civic.xml": sha256(meter_path)},
    }
    (ROOT / "display-profile.json").write_text(json.dumps(profile, indent=2) + "\n")


def make_samples():
    samples = {}
    for key, name in (("replay", "sample-replay.jsonl"),
                      ("dual", "sample-dual-screen.jsonl"),
                      ("captured", "sample-captured-pair.jsonl"),
                      ("liveCasting", "sample-live-casting-20260925.jsonl"),
                      ("wazeHeadunit", "sample-waze-headunit-20260925.jsonl"),
                      ("contract", "sample-contract-replay.jsonl"),
                      ("metadata", "sample-metadata-hypothesis.jsonl")):
        source = (ROOT / name).read_text()
        samples[key] = source
        for line in source.splitlines():
            if line.strip():
                json.loads(line)
    (ROOT / "samples.js").write_text("/* Generated by build_simulator_assets.py. */\nconst ClaritySamples = " + json.dumps(samples, separators=(",", ":")) + ";\n")


if __name__ == "__main__":
    make_profile()
    make_samples()
